services:
  - type: web
    name: zedox-bot
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MONGO_URI
        sync: false
